name = "Simple SMP Pack"
author = "DovisPas"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "292c908dfed6529e5ec4b7f8d8d852c9fd86373382bd1a9a9f0996f311a1d85c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
